name: "Custom Security Scanner"

# This is a dependant workflow, only executed after "build"
# workflow is successful. Otherwise, this workflow is skipped.

# Useful to run operations only on successfult builds.

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest
    container:
      image: github-sec-test/application:latest
    
    steps:
      - name: Test Command
        run: ls
