name: "Custom Security Scanner"

# This is a dependant workflow, only executed after "build"
# workflow is successful. Otherwise, this workflow is skipped.

# Useful to run operations only on successfult builds. Necessary
# for DAST-like use cases if the pipeline goes like:
# [build -> DAST checks -> publish]

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/application:latest
    
    steps:
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Get latest container image
        run: docker pull $IMAGE_ID

      - name: Run the image
        run: "docker run -d $IMAGE_ID"

      - name: Wait for container to fully start
        run: "until curl -s http://172.17.0.2:5000/ | grep 'Hello, World' > /dev/null 2>&1; do sleep 0.1; done;"

      - name: List docker images
        run: docker images -a

      - name: List docker containers
        run: docker ps -a

        # Will exit with code 1 if console is enabled
      - name: Check console endpoint
        run: "curl -i http://172.17.0.2:5000/console | grep -vz 'Werkzeug Debugger'"
